# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 746c5fa6b8c386ff6343dd90f5c10e39c8c428b0e3b2591943105e87ab5ff4ebeb59c55ef1496d3239eba1b2adf7cfaff4f08b70c8565f1dcc8a67a216132351

test:
  secret_key_base: 94b76c80516f787b88fb4dd678ad86c511e03d20d9a9d9670cc39dcd91d475995d3484fe2efd029a2dcb3025e5e3b3f47a1f57bf454cf1788e0cadfc6fa3f23c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
